name: Build README
description: Updates pipeline on schedule
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Update README
        run: |-
          node updator.js > README.md
          cat README.md
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "readme-bot@avestura.dev"
          git config --global user.name "README-bot"
          git add -A
          git commit -m "Update latest blog posts and snippets" || exit 0
          git push